BAU: ignore design system media query hack for lightningcss
The major upgrade to vite 8 changes a lot under the hood (including
moving from esbuild to rolldown - a different but also Rust based
transpiler/ bundler.

It also includes lightningcss out of the box which it now uses to
process our SCSS.

LightningCSS raises an exception when processing the design system:

```
[plugin vite:css-post]
SyntaxError: [lightningcss minify] Invalid media query.
This file contains @media zero hack (e.g. `@media (min-width: 0\0)`),
which was used in the past to support old Internet Explorer versions.
This is not a valid CSS syntax and will be ignored by modern browsers.
While this is not supported by LightningCSS, you can set
`css.lightningcss.errorRecovery: true` to strip these codes.
```

The design system using this is out of our control but I suspect its now
an outdated hack as the design system no longer officially support
internet explorer back too many generations.

We could raise an issue with the design system but in the meantime we
can configure vite to simply strip ignore this error for CSS and raise
it as a warning instead of a hard stop.